global:
  external_labels:
      monitor: 'prom-rancher'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - 0.0.0.0:1093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/etc/prometheus/rules/*.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 15s
    scrape_timeout: 10s

    static_configs:
    - targets: ['0.0.0.0:9090']

  - job_name: 'memb_cadv02'
    static_configs:
    - targets: ['0.0.0.0:1080']
      labels:
        instance: xxxx1urm02

  - job_name: 'memb_cadv01'
    static_configs:
    - targets: ['0.0.0.0:1080']
      labels:
        instance: xxxx1urm01

  - job_name: 'ship_cadv01'
    static_configs:
    - targets: ['0.0.0.0:1080']
      labels:
        instance: xxxx1rch01

  - job_name: 'memb_urm01'
    static_configs:
    - targets: ['0.0.0.0:9100']
      labels:
        instance: xxxx1urm01

  - job_name: 'memb_urm02'
    static_configs:
    - targets: ['0.0.0.0:9100']
      labels:
        instance: xxxx1urm02
    
  - job_name: 'ship_rch01'
    static_configs:
    - targets: ['0.0.0.0:9100']
      labels:
        instance: xxxx1rch01
